### ISSUE TITLE
broken link : "Open License 1.0 (in French)"

### ISSUE THREAD

**Issue by dzc34** [DISIC/rgaa_referentiel_en#13]
http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence
is redirected to https://www.data.gouv.fr/fr/faq/

The following URL is correct?
http://www.etalab.gouv.fr/licence-ouverte-open-licence

**Comment by philippeBron** [comment]
fixed.
Thank you for the warning.
