### ISSUE TITLE
Error 404 for some external links

### ISSUE THREAD

**Issue by dzc34** [DISIC/rgaa_referentiel_en#8]
Error 404 for some external links
tested with [validator.w3.org/checklink](https://validator.w3.org/checklink?uri=http%3A%2F%2Fdisic.github.io%2Frgaa_referentiel_en%2FRGAA3.0_Criteria_English_version_v1.html&hide_type=all&recursive=on&depth=&check=Check)
## in [Criteria](http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Criteria_English_version_v1.html)
- "F62" http://www.w3.org/TR/WCAG-TECHS/F62.htm -
- "F17" http://www.w3.org/TR/WCAG-TECHS/F17.html -
## in [Particular_cases](http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Particular_cases_English_version_v1.html)
-  "Accessible Rich Internet Applications (WAI-ARIA) 1.1" http://rawgit.com/w3c/aria/master/spec/aria.html  -
## in [ References](http://disic.github.io/rgaa_referentiel_en/RGAA3.0_References_English_version_v1.html)
- "online French academy contact form (in French)" http://www.academie-francaise.fr/contact/dico.asp

**Comment by philippeBron** [comment]
Issue fixed.
