### ISSUE TITLE
broken URI fragments (such as index.html#fragment)

### ISSUE THREAD

**Issue by dzc34** [DISIC/rgaa_referentiel_en#9]
broken URI fragments (such as index.html#fragment)
tested with [validator.w3.org/checklink](https://validator.w3.org/checklink?uri=http%3A%2F%2Fdisic.github.io%2Frgaa_referentiel_en%2FRGAA3.0_Criteria_English_version_v1.html&hide_type=all&recursive=on&depth=&check=Check)
## in [Criteria](http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Criteria_English_version_v1.html)

Broken fragments:
-      http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Glossary_English_version_v1.html#mAbbr 
-      http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Glossary_English_version_v1.html#mBlocCite 
-      http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Glossary_English_version_v1.html#mControleConsult 
-      http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Glossary_English_version_v1.html#mPertinent 
-      http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Glossary_English_version_v1.html#mEnteteTab 
-  http://disic.github.io/rgaa_referentiel_en/RGAA3.0_Particular_cases_English_version_v1.html#cpCrit13-7

**Comment by philippeBron** [comment]
issue fixed.
